idf_component_register(
    SRCS
        "src/wifi_portal.c"
        "src/stock_data.c"
        "src/stock_ui.c"
        "src/font_stock_16.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        bsp_rlcd42
        lvgl
        esp_wifi
        esp_http_client
        esp_http_server
        dns_server
        nvs_flash
        esp_netif
        esp_event
    EMBED_FILES
        "index.html"
)
